### ISSUE TITLE
Give the test suite a thorough audit

### ISSUE THREAD

**Issue by mkollasch-vmware** [diem/explorer#113]
- [x] `BlockchainRestClient.test.ts`: test values used in only one test should be declared inside that test.
- [x] Should we move the `test_utils/` folder into `src` ?
- [x] `EventPage.test.tsx:75`: there's an assertion about some text being truncated. Seems like it could be brittle.
- [x] Various places: sometimes when using `jest.useFakeTimers()` it's declared above the module mocks, and sometimes below. Let's be consistent about that.
- [x] Various places: In tests that assert that mocked API functions are called with particular values, I suggest also having assertions about the number of times they were called.
- [x] `TxnDetailsPage.test.tsx:161` and elsewhere: we should replace some of these giant magic strings with variable references.
- [x] Should we split `TransactionVersion` and `AccountAddress` components out from `Link.tsx`?
- [x] Also: `Link.test.tsx` does not appear to contain any direct tests for the Link component.
- [x] `IntegrationTestApiServerTools.ts` has several functions with unused parameters. Not sure why.
- [x] Wondering if it'd be worth an effort to increase the specificity of some acceptance test assertions.
- [x] Several custom query types in `src/api_clients/AnalyticsQuesries.ts` such as `AccountBalancesQueryType` are unused
- [x] `postForTop10Accounts.json` has a priority field in the Wiremock stub. However, this query is not ambiguous. There's no other query for accounts_balances. For this reason the priority is not necessary. (The other two places that priority is used, it's because one of them has a more specific query, but Wiremock can't tell that it's more specific.)

**Comment by gthoma17** [comment]
Demo: https://github.com/diem/explorer/pull/114/files
