### ISSUE TITLE
Address page breaks out the Event handles published under this address

### ISSUE THREAD

**Issue by gthoma17** [diem/explorer#41]
Business/User Value: As an Explorer of Diem I want to see Event handles published under this address so that I can debug more quickly 

### Acceptance Criteria
**GIVEN** an account exists
**WHEN** I view that account's page
**THEN** the Event handles get displayed in raw format in a list

**DEV NOTES**

**Comment by mkollasch-vmware** [comment]
What is an event handle?

Some accounts have resources called `EventHandleGenerator`, with an `addr` and a `counter`; is that the same thing? What should be displayed, and where?

**Comment by gthoma17** [comment]
https://user-images.githubusercontent.com/1739196/145087683-3f1b8eb0-f558-4ba0-b5fb-1df61f6bf428.mov
