### ISSUE TITLE
Diem in Circulation card shows the historical diem in circulation graph

### ISSUE THREAD

**Issue by gthoma17** [diem/explorer#45]
Business/User Value: As an Explorer of Diem I want to see the historical amount of diem in circulation so that I can get a sense for how today's volume compares

### Acceptance Criteria
**GIVEN** I am on the page which displays the Diem in circulation
**THEN** I also see a graph displaying how much Diem has been in circulation for the last week

**DEV NOTES**
* Determine a good time window size

**Comment by gthoma17** [comment]
@mkollasch-vmware @Izakey I went to create a UI demo for IPM for this story and noticed that the graph being drawn doesn't have any data.

I dug a bit and found that the source table `diem_in_circulation_dynamic` hasn't gotten any new rows since October. 

Would y'all mind investigating that as part of this story?

**Comment by mkollasch-vmware** [comment]
The PR discusses our response to that. When there's no data in the past week, it renders the current value and the current date as a single point. There doesn't seem to be a good way to handle it.

**Comment by gthoma17** [comment]
https://user-images.githubusercontent.com/1739196/145087661-c400d759-cbb4-4267-b6bc-739dbd2bf0a4.mov
