### ISSUE TITLE
Leaderboard page should display Top 10 transfers in the last 24 hours

### ISSUE THREAD

**Issue by gthoma17** [diem/explorer#56]
Business/User Value: As an Explorer of Diem I want to the largest transactions that have happened in the last day so that I can look for suspicious activity

### Acceptance Criteria
**GIVEN** I am on the leaderboard page
**THEN** I see a table listing the 10 largest transactions in the last 24 hours

**DESIGN NOTES**
The table should display: 
* Ranking
* Version # (as a link)
* Amount

**DEV NOTES**
[Relevant technical notes that developers may ask you to add to the story during weekly prep meeting (pre-IPM or IPM); sometimes they may add these themselves or add them as tasks]
[Indexer team still to work on queries to obtain data from `hourly_transfer` table]

**Comment by mkollasch-vmware** [comment]
Work on the Explorer side of this won't get far until https://github.com/diem/operations/issues/2627 is deployed.

**Comment by gthoma17** [comment]
https://user-images.githubusercontent.com/1739196/144659332-664eadcc-bc90-4b7d-865a-c55e26ad6c32.mov
