### ISSUE TITLE
Move Diem In Circulation to Current statistics card on landing page

### ISSUE THREAD

**Issue by Izakey** [diem/explorer#77]
Business/User Value: As an Explorer of Diem I want to see total XUS in circulation on the current statistics card on the landing page so that I can get sense for how active the blockchain is.

### Acceptance Criteria
**GIVEN** I'm on the landing page
**WHEN** The statistics card loads
**THEN** I see a statistic which represents the most recent data about the amount of XUS In Circulation
**AND** It is labeled "XUS In Circulation"

**DEV NOTES**
The statistic is already there. Just change the label.

**Comment by mkollasch-vmware** [comment]
What about the other content on the Diem In Circulation page, like the chart of historical data?

**Comment by gthoma17** [comment]
https://user-images.githubusercontent.com/1739196/145629690-2b5a86ec-d600-435b-bb40-517e872bc298.mov
